// Code generated by MockGen. DO NOT EDIT.
// Source: ChessLI/internal/persistence/profile (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=repository_mock.go -package=profile -mock_names=Repository=MockProfileRepository ChessLI/internal/persistence/profile Repository
//

// Package profile is a generated GoMock package.
package profile

import (
	identity "ChessLI/internal/identity"
	profile "ChessLI/internal/profile"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProfileRepository is a mock of Repository interface.
type MockProfileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProfileRepositoryMockRecorder
	isgomock struct{}
}

// MockProfileRepositoryMockRecorder is the mock recorder for MockProfileRepository.
type MockProfileRepositoryMockRecorder struct {
	mock *MockProfileRepository
}

// NewMockProfileRepository creates a new mock instance.
func NewMockProfileRepository(ctrl *gomock.Controller) *MockProfileRepository {
	mock := &MockProfileRepository{ctrl: ctrl}
	mock.recorder = &MockProfileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileRepository) EXPECT() *MockProfileRepositoryMockRecorder {
	return m.recorder
}

// CreateProfile mocks base method.
func (m *MockProfileRepository) CreateProfile(ctx context.Context, username, email, passwordHash string) (profile.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProfile", ctx, username, email, passwordHash)
	ret0, _ := ret[0].(profile.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProfile indicates an expected call of CreateProfile.
func (mr *MockProfileRepositoryMockRecorder) CreateProfile(ctx, username, email, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProfile", reflect.TypeOf((*MockProfileRepository)(nil).CreateProfile), ctx, username, email, passwordHash)
}

// GetCredentialByEmail mocks base method.
func (m *MockProfileRepository) GetCredentialByEmail(ctx context.Context, email string) (profile.LoginCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredentialByEmail", ctx, email)
	ret0, _ := ret[0].(profile.LoginCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCredentialByEmail indicates an expected call of GetCredentialByEmail.
func (mr *MockProfileRepositoryMockRecorder) GetCredentialByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredentialByEmail", reflect.TypeOf((*MockProfileRepository)(nil).GetCredentialByEmail), ctx, email)
}

// GetProfileByID mocks base method.
func (m *MockProfileRepository) GetProfileByID(ctx context.Context, iid identity.ProfileID) (profile.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileByID", ctx, iid)
	ret0, _ := ret[0].(profile.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileByID indicates an expected call of GetProfileByID.
func (mr *MockProfileRepositoryMockRecorder) GetProfileByID(ctx, iid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileByID", reflect.TypeOf((*MockProfileRepository)(nil).GetProfileByID), ctx, iid)
}

// GetProfilesByIDs mocks base method.
func (m *MockProfileRepository) GetProfilesByIDs(ctx context.Context, ids []identity.ProfileID) ([]profile.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfilesByIDs", ctx, ids)
	ret0, _ := ret[0].([]profile.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfilesByIDs indicates an expected call of GetProfilesByIDs.
func (mr *MockProfileRepositoryMockRecorder) GetProfilesByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfilesByIDs", reflect.TypeOf((*MockProfileRepository)(nil).GetProfilesByIDs), ctx, ids)
}
