// Code generated by MockGen. DO NOT EDIT.
// Source: ChessLI/internal/gameplay (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=service_mock.go -package=gameplay ChessLI/internal/gameplay Service
//

// Package gameplay is a generated GoMock package.
package gameplay

import (
	identity "ChessLI/internal/identity"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreatePrivateGame mocks base method.
func (m *MockService) CreatePrivateGame(ctx context.Context, command CreatePrivateCommand) (CreateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePrivateGame", ctx, command)
	ret0, _ := ret[0].(CreateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePrivateGame indicates an expected call of CreatePrivateGame.
func (mr *MockServiceMockRecorder) CreatePrivateGame(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePrivateGame", reflect.TypeOf((*MockService)(nil).CreatePrivateGame), ctx, command)
}

// EnterMatchmaking mocks base method.
func (m *MockService) EnterMatchmaking(ctx context.Context, command EnterMatchmakingCommand) (MatchTicket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnterMatchmaking", ctx, command)
	ret0, _ := ret[0].(MatchTicket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnterMatchmaking indicates an expected call of EnterMatchmaking.
func (mr *MockServiceMockRecorder) EnterMatchmaking(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnterMatchmaking", reflect.TypeOf((*MockService)(nil).EnterMatchmaking), ctx, command)
}

// GameState mocks base method.
func (m *MockService) GameState(ctx context.Context, gameID identity.GameID) (GameSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GameState", ctx, gameID)
	ret0, _ := ret[0].(GameSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GameState indicates an expected call of GameState.
func (mr *MockServiceMockRecorder) GameState(ctx, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GameState", reflect.TypeOf((*MockService)(nil).GameState), ctx, gameID)
}

// JoinPrivateGame mocks base method.
func (m *MockService) JoinPrivateGame(ctx context.Context, command JoinPrivateCommand) (JoinResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinPrivateGame", ctx, command)
	ret0, _ := ret[0].(JoinResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JoinPrivateGame indicates an expected call of JoinPrivateGame.
func (mr *MockServiceMockRecorder) JoinPrivateGame(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinPrivateGame", reflect.TypeOf((*MockService)(nil).JoinPrivateGame), ctx, command)
}

// MakeMove mocks base method.
func (m *MockService) MakeMove(ctx context.Context, command MoveCommand) (GameSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeMove", ctx, command)
	ret0, _ := ret[0].(GameSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeMove indicates an expected call of MakeMove.
func (mr *MockServiceMockRecorder) MakeMove(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeMove", reflect.TypeOf((*MockService)(nil).MakeMove), ctx, command)
}
