// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: completed_games.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCompletedGame = `-- name: CreateCompletedGame :exec
INSERT INTO completed_games (
    id,
    white_profile_id,
    black_profile_id,
    initial_time_ms,
    increment_ms,
    outcome,
    termination,
    final_fen,
    completed_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
`

type CreateCompletedGameParams struct {
	ID             pgtype.UUID
	WhiteProfileID pgtype.UUID
	BlackProfileID pgtype.UUID
	InitialTimeMs  int64
	IncrementMs    int64
	Outcome        string
	Termination    string
	FinalFen       string
	CompletedAt    pgtype.Timestamptz
}

func (q *Queries) CreateCompletedGame(ctx context.Context, arg CreateCompletedGameParams) error {
	_, err := q.db.Exec(ctx, createCompletedGame,
		arg.ID,
		arg.WhiteProfileID,
		arg.BlackProfileID,
		arg.InitialTimeMs,
		arg.IncrementMs,
		arg.Outcome,
		arg.Termination,
		arg.FinalFen,
		arg.CompletedAt,
	)
	return err
}

const createCompletedGameMoves = `-- name: CreateCompletedGameMoves :exec
INSERT INTO completed_game_moves (game_id, ply, uci)
SELECT
    $1,
    moves.ply::INTEGER,
    moves.uci
FROM unnest($2::TEXT[]) WITH ORDINALITY AS moves(uci, ply)
`

type CreateCompletedGameMovesParams struct {
	GameID   pgtype.UUID
	UciMoves []string
}

func (q *Queries) CreateCompletedGameMoves(ctx context.Context, arg CreateCompletedGameMovesParams) error {
	_, err := q.db.Exec(ctx, createCompletedGameMoves, arg.GameID, arg.UciMoves)
	return err
}

const getCompletedGameByID = `-- name: GetCompletedGameByID :one
SELECT
    id,
    white_profile_id,
    black_profile_id,
    initial_time_ms,
    increment_ms,
    outcome,
    termination,
    final_fen,
    completed_at
FROM completed_games
WHERE id = $1
`

func (q *Queries) GetCompletedGameByID(ctx context.Context, id pgtype.UUID) (CompletedGame, error) {
	row := q.db.QueryRow(ctx, getCompletedGameByID, id)
	var i CompletedGame
	err := row.Scan(
		&i.ID,
		&i.WhiteProfileID,
		&i.BlackProfileID,
		&i.InitialTimeMs,
		&i.IncrementMs,
		&i.Outcome,
		&i.Termination,
		&i.FinalFen,
		&i.CompletedAt,
	)
	return i, err
}

const listCompletedGameMovesByGameID = `-- name: ListCompletedGameMovesByGameID :many
SELECT ply, uci
FROM completed_game_moves
WHERE game_id = $1
ORDER BY ply
`

type ListCompletedGameMovesByGameIDRow struct {
	Ply int32
	Uci string
}

func (q *Queries) ListCompletedGameMovesByGameID(ctx context.Context, gameID pgtype.UUID) ([]ListCompletedGameMovesByGameIDRow, error) {
	rows, err := q.db.Query(ctx, listCompletedGameMovesByGameID, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompletedGameMovesByGameIDRow
	for rows.Next() {
		var i ListCompletedGameMovesByGameIDRow
		if err := rows.Scan(&i.Ply, &i.Uci); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletedGamesByProfileID = `-- name: ListCompletedGamesByProfileID :many
SELECT
    id,
    white_profile_id,
    black_profile_id,
    initial_time_ms,
    increment_ms,
    outcome,
    termination,
    completed_at
FROM completed_games
WHERE white_profile_id = $1
   OR black_profile_id = $1
ORDER BY completed_at DESC, id DESC
LIMIT $3
OFFSET $2
`

type ListCompletedGamesByProfileIDParams struct {
	ProfileID  pgtype.UUID
	PageOffset int32
	PageSize   int32
}

type ListCompletedGamesByProfileIDRow struct {
	ID             pgtype.UUID
	WhiteProfileID pgtype.UUID
	BlackProfileID pgtype.UUID
	InitialTimeMs  int64
	IncrementMs    int64
	Outcome        string
	Termination    string
	CompletedAt    pgtype.Timestamptz
}

func (q *Queries) ListCompletedGamesByProfileID(ctx context.Context, arg ListCompletedGamesByProfileIDParams) ([]ListCompletedGamesByProfileIDRow, error) {
	rows, err := q.db.Query(ctx, listCompletedGamesByProfileID, arg.ProfileID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompletedGamesByProfileIDRow
	for rows.Next() {
		var i ListCompletedGamesByProfileIDRow
		if err := rows.Scan(
			&i.ID,
			&i.WhiteProfileID,
			&i.BlackProfileID,
			&i.InitialTimeMs,
			&i.IncrementMs,
			&i.Outcome,
			&i.Termination,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
