// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type CompletedGame struct {
	ID             uuid.UUID
	WhiteProfileID uuid.UUID
	BlackProfileID uuid.UUID
	InitialTimeMs  int64
	IncrementMs    int64
	Outcome        string
	Termination    string
	FinalFen       string
	CompletedAt    time.Time
}

type CompletedGameMove struct {
	GameID           uuid.UUID
	Ply              int32
	Uci              string
	WhiteRemainingMs int64
	BlackRemainingMs int64
}

type Profile struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}
