// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CompletedGame struct {
	ID             pgtype.UUID
	WhiteProfileID pgtype.UUID
	BlackProfileID pgtype.UUID
	InitialTimeMs  int64
	IncrementMs    int64
	Outcome        string
	Termination    string
	FinalFen       string
	CompletedAt    pgtype.Timestamptz
}

type CompletedGameMove struct {
	GameID pgtype.UUID
	Ply    int32
	Uci    string
}

type Profile struct {
	ID           pgtype.UUID
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}
