// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (
    id, username, email, password_hash
)
VALUES (
    $1, $2, $3, $4
)
RETURNING id, username, email, created_at
`

type CreateProfileParams struct {
	ID           pgtype.UUID
	Username     string
	Email        string
	PasswordHash string
}

type CreateProfileRow struct {
	ID        pgtype.UUID
	Username  string
	Email     string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (CreateProfileRow, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
	)
	var i CreateProfileRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getProfileByEmailForLogin = `-- name: GetProfileByEmailForLogin :one
SELECT id, password_hash
FROM profiles
WHERE email = $1
`

type GetProfileByEmailForLoginRow struct {
	ID           pgtype.UUID
	PasswordHash string
}

func (q *Queries) GetProfileByEmailForLogin(ctx context.Context, email string) (GetProfileByEmailForLoginRow, error) {
	row := q.db.QueryRow(ctx, getProfileByEmailForLogin, email)
	var i GetProfileByEmailForLoginRow
	err := row.Scan(&i.ID, &i.PasswordHash)
	return i, err
}

const getProfileByID = `-- name: GetProfileByID :one
SELECT id, username, email, created_at
FROM profiles
WHERE id = $1
`

type GetProfileByIDRow struct {
	ID        pgtype.UUID
	Username  string
	Email     string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetProfileByID(ctx context.Context, id pgtype.UUID) (GetProfileByIDRow, error) {
	row := q.db.QueryRow(ctx, getProfileByID, id)
	var i GetProfileByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getProfilesByIDs = `-- name: GetProfilesByIDs :many
SELECT id, username, email, created_at
FROM profiles
WHERE id = ANY($1::UUID[])
ORDER BY id
`

type GetProfilesByIDsRow struct {
	ID        pgtype.UUID
	Username  string
	Email     string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetProfilesByIDs(ctx context.Context, ids []pgtype.UUID) ([]GetProfilesByIDsRow, error) {
	rows, err := q.db.Query(ctx, getProfilesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProfilesByIDsRow
	for rows.Next() {
		var i GetProfilesByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
