// Code generated by MockGen. DO NOT EDIT.
// Source: ChessLI/internal/persistence/game (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=repository_mock.go -package=game -mock_names=Repository=MockGameRepository ChessLI/internal/persistence/game Repository
//

// Package game is a generated GoMock package.
package game

import (
	game "ChessLI/internal/game"
	identity "ChessLI/internal/identity"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGameRepository is a mock of Repository interface.
type MockGameRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGameRepositoryMockRecorder
	isgomock struct{}
}

// MockGameRepositoryMockRecorder is the mock recorder for MockGameRepository.
type MockGameRepositoryMockRecorder struct {
	mock *MockGameRepository
}

// NewMockGameRepository creates a new mock instance.
func NewMockGameRepository(ctrl *gomock.Controller) *MockGameRepository {
	mock := &MockGameRepository{ctrl: ctrl}
	mock.recorder = &MockGameRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameRepository) EXPECT() *MockGameRepositoryMockRecorder {
	return m.recorder
}

// CreateGame mocks base method.
func (m *MockGameRepository) CreateGame(ctx context.Context, arg1 game.CompletedGame) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGame", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateGame indicates an expected call of CreateGame.
func (mr *MockGameRepositoryMockRecorder) CreateGame(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGame", reflect.TypeOf((*MockGameRepository)(nil).CreateGame), ctx, arg1)
}

// CreateMoves mocks base method.
func (m *MockGameRepository) CreateMoves(ctx context.Context, gameID identity.GameID, moves []game.Move) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMoves", ctx, gameID, moves)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMoves indicates an expected call of CreateMoves.
func (mr *MockGameRepositoryMockRecorder) CreateMoves(ctx, gameID, moves any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMoves", reflect.TypeOf((*MockGameRepository)(nil).CreateMoves), ctx, gameID, moves)
}

// GetGameByID mocks base method.
func (m *MockGameRepository) GetGameByID(ctx context.Context, gameID identity.GameID) (game.CompletedGame, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGameByID", ctx, gameID)
	ret0, _ := ret[0].(game.CompletedGame)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGameByID indicates an expected call of GetGameByID.
func (mr *MockGameRepositoryMockRecorder) GetGameByID(ctx, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGameByID", reflect.TypeOf((*MockGameRepository)(nil).GetGameByID), ctx, gameID)
}

// ListGamesByProfileID mocks base method.
func (m *MockGameRepository) ListGamesByProfileID(ctx context.Context, profileID identity.ProfileID, pageOffset, pageSize int32) ([]game.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGamesByProfileID", ctx, profileID, pageOffset, pageSize)
	ret0, _ := ret[0].([]game.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGamesByProfileID indicates an expected call of ListGamesByProfileID.
func (mr *MockGameRepositoryMockRecorder) ListGamesByProfileID(ctx, profileID, pageOffset, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGamesByProfileID", reflect.TypeOf((*MockGameRepository)(nil).ListGamesByProfileID), ctx, profileID, pageOffset, pageSize)
}

// ListMovesByGameID mocks base method.
func (m *MockGameRepository) ListMovesByGameID(ctx context.Context, gameID identity.GameID) ([]game.Move, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMovesByGameID", ctx, gameID)
	ret0, _ := ret[0].([]game.Move)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMovesByGameID indicates an expected call of ListMovesByGameID.
func (mr *MockGameRepositoryMockRecorder) ListMovesByGameID(ctx, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMovesByGameID", reflect.TypeOf((*MockGameRepository)(nil).ListMovesByGameID), ctx, gameID)
}
