// Code generated by MockGen. DO NOT EDIT.
// Source: ChessLI/internal/persistence/game (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=repository_mock.go -package=game -mock_names=Repository=MockGameRepository ChessLI/internal/persistence/game Repository
//

// Package game is a generated GoMock package.
package game

import (
	game "ChessLI/internal/game"
	identity "ChessLI/internal/identity"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGameRepository is a mock of Repository interface.
type MockGameRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGameRepositoryMockRecorder
	isgomock struct{}
}

// MockGameRepositoryMockRecorder is the mock recorder for MockGameRepository.
type MockGameRepositoryMockRecorder struct {
	mock *MockGameRepository
}

// NewMockGameRepository creates a new mock instance.
func NewMockGameRepository(ctrl *gomock.Controller) *MockGameRepository {
	mock := &MockGameRepository{ctrl: ctrl}
	mock.recorder = &MockGameRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameRepository) EXPECT() *MockGameRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGameRepository) Create(ctx context.Context, arg1 game.Game) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockGameRepositoryMockRecorder) Create(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGameRepository)(nil).Create), ctx, arg1)
}

// CreateMoves mocks base method.
func (m *MockGameRepository) CreateMoves(ctx context.Context, gameID identity.GameID, moves []game.Move) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMoves", ctx, gameID, moves)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMoves indicates an expected call of CreateMoves.
func (mr *MockGameRepositoryMockRecorder) CreateMoves(ctx, gameID, moves any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMoves", reflect.TypeOf((*MockGameRepository)(nil).CreateMoves), ctx, gameID, moves)
}

// GetByID mocks base method.
func (m *MockGameRepository) GetByID(ctx context.Context, gameID identity.GameID) (game.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, gameID)
	ret0, _ := ret[0].(game.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockGameRepositoryMockRecorder) GetByID(ctx, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockGameRepository)(nil).GetByID), ctx, gameID)
}

// ListByProfileID mocks base method.
func (m *MockGameRepository) ListByProfileID(ctx context.Context, profileID identity.ProfileID, pageOffset, pageSize int32) ([]game.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByProfileID", ctx, profileID, pageOffset, pageSize)
	ret0, _ := ret[0].([]game.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByProfileID indicates an expected call of ListByProfileID.
func (mr *MockGameRepositoryMockRecorder) ListByProfileID(ctx, profileID, pageOffset, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByProfileID", reflect.TypeOf((*MockGameRepository)(nil).ListByProfileID), ctx, profileID, pageOffset, pageSize)
}

// ListMovesByGameID mocks base method.
func (m *MockGameRepository) ListMovesByGameID(ctx context.Context, gameID identity.GameID) ([]game.Move, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMovesByGameID", ctx, gameID)
	ret0, _ := ret[0].([]game.Move)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMovesByGameID indicates an expected call of ListMovesByGameID.
func (mr *MockGameRepositoryMockRecorder) ListMovesByGameID(ctx, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMovesByGameID", reflect.TypeOf((*MockGameRepository)(nil).ListMovesByGameID), ctx, gameID)
}
