// Code generated by MockGen. DO NOT EDIT.
// Source: board_view.go
//
// Generated by this command:
//
//	mockgen -source=board_view.go -destination=board_view_mock.go -package=models
//

// Package models is a generated GoMock package.
package models

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBoardView is a mock of BoardView interface.
type MockBoardView struct {
	ctrl     *gomock.Controller
	recorder *MockBoardViewMockRecorder
	isgomock struct{}
}

// MockBoardViewMockRecorder is the mock recorder for MockBoardView.
type MockBoardViewMockRecorder struct {
	mock *MockBoardView
}

// NewMockBoardView creates a new mock instance.
func NewMockBoardView(ctrl *gomock.Controller) *MockBoardView {
	mock := &MockBoardView{ctrl: ctrl}
	mock.recorder = &MockBoardViewMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBoardView) EXPECT() *MockBoardViewMockRecorder {
	return m.recorder
}

// SpotAt mocks base method.
func (m *MockBoardView) SpotAt(pos Position) *Spot {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpotAt", pos)
	ret0, _ := ret[0].(*Spot)
	return ret0
}

// SpotAt indicates an expected call of SpotAt.
func (mr *MockBoardViewMockRecorder) SpotAt(pos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpotAt", reflect.TypeOf((*MockBoardView)(nil).SpotAt), pos)
}
