// Code generated by MockGen. DO NOT EDIT.
// Source: piece.go
//
// Generated by this command:
//
//	mockgen -source=piece.go -destination=piece_mock.go -package=models
//

// Package models is a generated GoMock package.
package models

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPiece is a mock of Piece interface.
type MockPiece struct {
	ctrl     *gomock.Controller
	recorder *MockPieceMockRecorder
	isgomock struct{}
}

// MockPieceMockRecorder is the mock recorder for MockPiece.
type MockPieceMockRecorder struct {
	mock *MockPiece
}

// NewMockPiece creates a new mock instance.
func NewMockPiece(ctrl *gomock.Controller) *MockPiece {
	mock := &MockPiece{ctrl: ctrl}
	mock.recorder = &MockPieceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPiece) EXPECT() *MockPieceMockRecorder {
	return m.recorder
}

// AttackedSquares mocks base method.
func (m *MockPiece) AttackedSquares(board BoardView) []Position {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttackedSquares", board)
	ret0, _ := ret[0].([]Position)
	return ret0
}

// AttackedSquares indicates an expected call of AttackedSquares.
func (mr *MockPieceMockRecorder) AttackedSquares(board any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttackedSquares", reflect.TypeOf((*MockPiece)(nil).AttackedSquares), board)
}

// Color mocks base method.
func (m *MockPiece) Color() Color {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Color")
	ret0, _ := ret[0].(Color)
	return ret0
}

// Color indicates an expected call of Color.
func (mr *MockPieceMockRecorder) Color() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Color", reflect.TypeOf((*MockPiece)(nil).Color))
}

// MoveTo mocks base method.
func (m *MockPiece) MoveTo(position Position) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MoveTo", position)
}

// MoveTo indicates an expected call of MoveTo.
func (mr *MockPieceMockRecorder) MoveTo(position any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveTo", reflect.TypeOf((*MockPiece)(nil).MoveTo), position)
}

// Position mocks base method.
func (m *MockPiece) Position() Position {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Position")
	ret0, _ := ret[0].(Position)
	return ret0
}

// Position indicates an expected call of Position.
func (mr *MockPieceMockRecorder) Position() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Position", reflect.TypeOf((*MockPiece)(nil).Position))
}

// PossibleMoves mocks base method.
func (m *MockPiece) PossibleMoves(board BoardView) []Position {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PossibleMoves", board)
	ret0, _ := ret[0].([]Position)
	return ret0
}

// PossibleMoves indicates an expected call of PossibleMoves.
func (mr *MockPieceMockRecorder) PossibleMoves(board any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PossibleMoves", reflect.TypeOf((*MockPiece)(nil).PossibleMoves), board)
}

// String mocks base method.
func (m *MockPiece) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockPieceMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockPiece)(nil).String))
}

// Type mocks base method.
func (m *MockPiece) Type() PieceType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(PieceType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockPieceMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockPiece)(nil).Type))
}
