// Code generated by MockGen. DO NOT EDIT.
// Source: ChessLI/internal/gameplay (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=../websocket/game_service_mock.go -package=websocket -mock_names=Service=MockGameService ChessLI/internal/gameplay Service
//

// Package websocket is a generated GoMock package.
package websocket

import (
	gameplay "ChessLI/internal/gameplay"
	identity "ChessLI/internal/identity"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGameService is a mock of Service interface.
type MockGameService struct {
	ctrl     *gomock.Controller
	recorder *MockGameServiceMockRecorder
	isgomock struct{}
}

// MockGameServiceMockRecorder is the mock recorder for MockGameService.
type MockGameServiceMockRecorder struct {
	mock *MockGameService
}

// NewMockGameService creates a new mock instance.
func NewMockGameService(ctrl *gomock.Controller) *MockGameService {
	mock := &MockGameService{ctrl: ctrl}
	mock.recorder = &MockGameServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameService) EXPECT() *MockGameServiceMockRecorder {
	return m.recorder
}

// CreatePrivateGame mocks base method.
func (m *MockGameService) CreatePrivateGame(ctx context.Context, command gameplay.CreatePrivateCommand) (gameplay.CreateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePrivateGame", ctx, command)
	ret0, _ := ret[0].(gameplay.CreateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePrivateGame indicates an expected call of CreatePrivateGame.
func (mr *MockGameServiceMockRecorder) CreatePrivateGame(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePrivateGame", reflect.TypeOf((*MockGameService)(nil).CreatePrivateGame), ctx, command)
}

// EnterMatchmaking mocks base method.
func (m *MockGameService) EnterMatchmaking(ctx context.Context, command gameplay.EnterMatchmakingCommand) (gameplay.MatchTicket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnterMatchmaking", ctx, command)
	ret0, _ := ret[0].(gameplay.MatchTicket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnterMatchmaking indicates an expected call of EnterMatchmaking.
func (mr *MockGameServiceMockRecorder) EnterMatchmaking(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnterMatchmaking", reflect.TypeOf((*MockGameService)(nil).EnterMatchmaking), ctx, command)
}

// GameState mocks base method.
func (m *MockGameService) GameState(ctx context.Context, gameID identity.GameID) (gameplay.GameSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GameState", ctx, gameID)
	ret0, _ := ret[0].(gameplay.GameSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GameState indicates an expected call of GameState.
func (mr *MockGameServiceMockRecorder) GameState(ctx, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GameState", reflect.TypeOf((*MockGameService)(nil).GameState), ctx, gameID)
}

// JoinPrivateGame mocks base method.
func (m *MockGameService) JoinPrivateGame(ctx context.Context, command gameplay.JoinPrivateCommand) (gameplay.JoinResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinPrivateGame", ctx, command)
	ret0, _ := ret[0].(gameplay.JoinResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JoinPrivateGame indicates an expected call of JoinPrivateGame.
func (mr *MockGameServiceMockRecorder) JoinPrivateGame(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinPrivateGame", reflect.TypeOf((*MockGameService)(nil).JoinPrivateGame), ctx, command)
}

// MakeMove mocks base method.
func (m *MockGameService) MakeMove(ctx context.Context, command gameplay.MoveCommand) (gameplay.GameSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeMove", ctx, command)
	ret0, _ := ret[0].(gameplay.GameSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeMove indicates an expected call of MakeMove.
func (mr *MockGameServiceMockRecorder) MakeMove(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeMove", reflect.TypeOf((*MockGameService)(nil).MakeMove), ctx, command)
}
