// Code generated by MockGen. DO NOT EDIT.
// Source: move_service.go
//
// Generated by this command:
//
//	mockgen -source=move_service.go -destination=move_service_mock.go -package=moves
//

// Package moves is a generated GoMock package.
package moves

import (
	models "chessli/internal/chess/board/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMoveService is a mock of MoveService interface.
type MockMoveService struct {
	ctrl     *gomock.Controller
	recorder *MockMoveServiceMockRecorder
	isgomock struct{}
}

// MockMoveServiceMockRecorder is the mock recorder for MockMoveService.
type MockMoveServiceMockRecorder struct {
	mock *MockMoveService
}

// NewMockMoveService creates a new mock instance.
func NewMockMoveService(ctrl *gomock.Controller) *MockMoveService {
	mock := &MockMoveService{ctrl: ctrl}
	mock.recorder = &MockMoveServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMoveService) EXPECT() *MockMoveServiceMockRecorder {
	return m.recorder
}

// ApplyMove mocks base method.
func (m *MockMoveService) ApplyMove(move models.ResolvedMove) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ApplyMove", move)
}

// ApplyMove indicates an expected call of ApplyMove.
func (mr *MockMoveServiceMockRecorder) ApplyMove(move any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyMove", reflect.TypeOf((*MockMoveService)(nil).ApplyMove), move)
}

// ResolveMove mocks base method.
func (m *MockMoveService) ResolveMove(move models.Move) (models.ResolvedMove, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveMove", move)
	ret0, _ := ret[0].(models.ResolvedMove)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveMove indicates an expected call of ResolveMove.
func (mr *MockMoveServiceMockRecorder) ResolveMove(move any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveMove", reflect.TypeOf((*MockMoveService)(nil).ResolveMove), move)
}

// RevertMove mocks base method.
func (m *MockMoveService) RevertMove(move models.ResolvedMove) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RevertMove", move)
}

// RevertMove indicates an expected call of RevertMove.
func (mr *MockMoveServiceMockRecorder) RevertMove(move any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevertMove", reflect.TypeOf((*MockMoveService)(nil).RevertMove), move)
}
